### ISSUE TITLE
bot_name not respected

### ISSUE THREAD

**Issue by clfsoft** [ahelal/bender#13]
for example ,even I specified releasebot, it still refere to bender
- name: slack-trigger
  type: bender-resource
  source:
    slack_token : {{slack-bot-token}}
    bot_name: "releasebot"

fly -t xxx check-resource --resource  yyy/slack-trigger
error: check failed with exit status '1':
Unable to find bot name 'bender'

**Comment by clfsoft** [comment]
should specified
as_user: false

**Comment by ahelal** [comment]
@clfsoft if it is not clear in the docs, It would be helpful if you suggest doc change to reflect that.

**Comment by clfsoft** [comment]
@ahelal  
in my mind , even as_user: true , I still can configure bot_name. 
But this shoud become a feature request, because the document is clear about that.
